### ISSUE TITLE
Improve image quality of QR codes 

### ISSUE THREAD

**Issue by bakersemail** [djag-qld/documentproduction#82]
QR codes appear blurry when zoomed out due to PDF rastering.

Investigate how we can improve the image quality of QR codes when rendering on screens as they currently print fine.

**Comment by duttonw** [comment]
https://www.qr-code-generator.com/blog/qr-code-scanning-problems-and-solutions/
See if you can change from png to svg for the qr code generation 

in this function:
https://github.com/qld-gov-au/documentproduction/blob/145e86d65babe52f208e3230d50a9f4c01ba23d1/app/src/main/java/au/gov/qld/bdm/documentproduction/document/BarcodeElementFactory.java#L73

QRCode does have
```
    public void svg(OutputStream outs) {
        try {
            MatrixToSvgWriter.writeToStream(this.createMatrix(this.text), outs, this.matrixToImageConfig);
        } catch (Exception var3) {
            throw new QRGenerationException("Failed to create QR svg from text due to underlying exception", var3);
        }
    }
```

You may also need to set width/height in the qr code generator
